import DashboardIcon from "@mui/icons-material/Dashboard";
import AutoStoriesIcon from "@mui/icons-material/AutoStories";
import HikingIcon from "@mui/icons-material/Hiking";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import MapIcon from "@mui/icons-material/Map";
import RateReviewIcon from "@mui/icons-material/RateReview";
import ArticleIcon from "@mui/icons-material/Article";
import SettingsIcon from "@mui/icons-material/Settings";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import MobileFriendlyIcon from "@mui/icons-material/MobileFriendly";
import RouteIcon from "@mui/icons-material/Route";
import RemoveRedEyeIcon from "@mui/icons-material/RemoveRedEye";
import CurrencyExchangeIcon from "@mui/icons-material/CurrencyExchange";
import CollectionsIcon from "@mui/icons-material/Collections";
import ContactSupportIcon from "@mui/icons-material/ContactSupport";
import GroupsIcon from "@mui/icons-material/Groups";

export const navItems = [
  {
    id: "home",
    label: "Home",
    path: "/",
  },
  {
    id: "trekking",
    label: "Trekking",
    path: "/trekking",
  },
  {
    id: "kailashTours",
    label: "Kailash Tours",
    path: "/package/kjfdf",
  },
  {
    id: "aboutus",
    label: "About Us",
    path: "/aboutus",
  },
  {
    id: "activities",
    label: "Activities",
    path: "/activities",
  },
  {
    id: "dayTour",
    label: "Day Tour",
    path: "/day-tour",
  },
  {
    id: "nepalTour",
    label: "Nepal Tour",
    path: "/nepal-tour",
  },
  {
    id: "admin-dashboard",
    label: "Admin View",
    path: "/admin",
  },
  {
    id: "contact",
    label: "Contact",
    path: "/contact",
  },
];
export const adminNavItems = [
  {
    id: "dashboard",
    icon: <DashboardIcon />,
    label: "Dashboard",
    path: "",
  },
  {
    id: "pages",
    icon: <AutoStoriesIcon />,
    label: "Pages",
    path: "pages",
  },
  {
    id: "packages",
    icon: <HikingIcon />,
    label: "Packages",
    path: "packages",
  },
  {
    id: "destination",
    icon: <LocationOnIcon />,
    label: "Destination",
    path: "destination",
  },
  {
    id: "regions",
    icon: <MapIcon />,
    label: "Regions",
    path: "regions",
  },
  {
    id: "testimonials",
    icon: <RateReviewIcon />,
    label: "Testimonials",
    path: "testimonials",
  },
  {
    id: "blogs",
    icon: <ArticleIcon />,
    label: "Blogs",
    path: "blogs",
  },
  {
    id: "settings",
    icon: <SettingsIcon />,
    label: "Settings",
    path: "settings",
  },
  {
    id: "our-team",
    icon: <GroupsIcon />,
    label: "Our Team",
    path: "our-team",
  },
  {
    id: "bookings",
    icon: <MobileFriendlyIcon />,
    label: "Bookings",
    path: "bookings",
  },
  {
    id: "admins",
    icon: <AccountCircleIcon />,
    label: "Admins",
    path: "admins",
  },
];
export const registrationFormControls = [
  {
    id: "name",
    type: "text",
    label: "Full Name",
  },
  {
    id: "email",
    type: "email",
    label: "Email",
  },
  {
    id: "password",
    type: "password",
    label: "Password",
  },
];

export const loginFormControls = [
  {
    id: "email",
    type: "email",
    label: "Email",
  },
  {
    id: "password",
    type: "password",
    label: "Password",
  },
];
export const packageNavItems = [
  {
    id: "overview",
    icon: <RemoveRedEyeIcon />,
    label: "Overview",
    path: "#overview",
  },
  {
    id: "itinerary",
    icon: <RouteIcon />,
    label: "Itinerary",
    path: "#itinerary",
  },
  {
    id: "map",
    icon: <MapIcon />,
    label: "Map",
    path: "#map",
  },

  {
    id: "costInclueExclude",
    icon: <CurrencyExchangeIcon />,
    label: "Cost Include/Exclude",
    path: "#costInclueExclude",
  },
  {
    id: "gallery",
    icon: <CollectionsIcon />,
    label: "Gallery",
    path: "#gallery",
  },
  {
    id: "faq",
    icon: <ContactSupportIcon />,
    label: "FAQ",
    path: "#faq",
  },

  {
    id: "review",
    icon: <RateReviewIcon />,
    label: "Review",
    path: "#review",
  },
];

export const countries = [
  "Andorra",
  "French Southern and Antarctic Lands",
  "Laos",
  "Canada",
  "Nigeria",
  "Vanuatu",
  "Czechia",
  "Malawi",
  "Mali",
  "Iceland",
  "Norway",
  "Saint Vincent and the Grenadines",
  "Guadeloupe",
  "Chile",
  "Bermuda",
  "Kuwait",
  "Dominica",
  "Montenegro",
  "United States Virgin Islands",
  "Cameroon",
  "Sri Lanka",
  "China",
  "Bangladesh",
  "Sweden",
  "Grenada",
  "Turkey",
  "Guinea",
  "Tanzania",
  "Rwanda",
  "Singapore",
  "Morocco",
  "Saint Barthélemy",
  "Iraq",
  "Brunei",
  "Isle of Man",
  "North Korea",
  "Iran",
  "Curaçao",
  "Paraguay",
  "Albania",
  "Tajikistan",
  "Bolivia",
  "Austria",
  "Saint Kitts and Nevis",
  "United States Minor Outlying Islands",
  "Colombia",
  "Kosovo",
  "Belize",
  "Guinea-Bissau",
  "Marshall Islands",
  "Myanmar",
  "French Polynesia",
  "Brazil",
  "Croatia",
  "Somalia",
  "Afghanistan",
  "Anguilla",
  "Cook Islands",
  "New Zealand",
  "Eritrea",
  "Cambodia",
  "Bahamas",
  "Belarus",
  "Norfolk Island",
  "Tuvalu",
  "South Georgia",
  "Mauritania",
  "New Caledonia",
  "Bulgaria",
  "Mozambique",
  "Niue",
  "Estonia",
  "Italy",
  "Malta",
  "Slovenia",
  "India",
  "Peru",
  "Burundi",
  "Lithuania",
  "United States",
  "Honduras",
  "Tonga",
  "Saudi Arabia",
  "Suriname",
  "Qatar",
  "Gibraltar",
  "Northern Mariana Islands",
  "Mauritius",
  "Barbados",
  "Réunion",
  "British Indian Ocean Territory",
  "Syria",
  "Egypt",
  "São Tomé and Príncipe",
  "Kiribati",
  "Timor-Leste",
  "Lesotho",
  "Solomon Islands",
  "Libya",
  "South Korea",
  "Liechtenstein",
  "Nicaragua",
  "Ecuador",
  "Maldives",
  "Algeria",
  "Kyrgyzstan",
  "Finland",
  "Kenya",
  "Cuba",
  "Montserrat",
  "Poland",
  "Åland Islands",
  "Ethiopia",
  "Togo",
  "Bosnia and Herzegovina",
  "Uruguay",
  "Guam",
  "Cape Verde",
  "Chad",
  "Vatican City",
  "Palau",
  "Haiti",
  "Yemen",
  "Eswatini",
  "Zimbabwe",
  "Greece",
  "Israel",
  "Saint Martin",
  "Antigua and Barbuda",
  "Cyprus",
  "Sint Maarten",
  "Monaco",
  "Fiji",
  "Ukraine",
  "Martinique",
  "Hong Kong",
  "Portugal",
  "Bhutan",
  "Nepal",
  "France",
  "Ireland",
  "United Arab Emirates",
  "Guernsey",
  "Saint Lucia",
  "Dominican Republic",
  "Serbia",
  "Botswana",
  "Ivory Coast",
  "Ghana",
  "Comoros",
  "Azerbaijan",
  "United Kingdom",
  "Central African Republic",
  "Palestine",
  "Caribbean Netherlands",
  "Taiwan",
  "Pitcairn Islands",
  "San Marino",
  "Svalbard and Jan Mayen",
  "Djibouti",
  "Wallis and Futuna",
  "Denmark",
  "Papua New Guinea",
  "Madagascar",
  "Bouvet Island",
  "Hungary",
  "Tokelau",
  "Trinidad and Tobago",
  "Gambia",
  "Luxembourg",
  "Cocos (Keeling) Islands",
  "Republic of the Congo",
  "Argentina",
  "DR Congo",
  "Greenland",
  "Jordan",
  "Belgium",
  "Switzerland",
  "Indonesia",
  "Lebanon",
  "Malaysia",
  "Cayman Islands",
  "Slovakia",
  "Armenia",
  "Christmas Island",
  "Mongolia",
  "Saint Pierre and Miquelon",
  "Japan",
  "South Africa",
  "Philippines",
  "Micronesia",
  "Germany",
  "Latvia",
  "Jamaica",
  "Macau",
  "Nauru",
  "Faroe Islands",
  "Guyana",
  "Burkina Faso",
  "Sudan",
  "Russia",
  "Mayotte",
  "Australia",
  "Liberia",
  "Mexico",
  "Tunisia",
  "Aruba",
  "Kazakhstan",
  "Oman",
  "French Guiana",
  "Niger",
  "Turkmenistan",
  "Sierra Leone",
  "Samoa",
  "Senegal",
  "Georgia",
  "Namibia",
  "South Sudan",
  "Thailand",
  "Bahrain",
  "Falkland Islands",
  "Jersey",
  "Vietnam",
  "Guatemala",
  "Moldova",
  "North Macedonia",
  "Uzbekistan",
  "Romania",
  "Uganda",
  "El Salvador",
  "Zambia",
  "Gabon",
  "Equatorial Guinea",
  "Spain",
  "Netherlands",
  "British Virgin Islands",
  "Benin",
  "Pakistan",
  "Panama",
  "Turks and Caicos Islands",
  "Angola",
  "American Samoa",
  "Venezuela",
  "Costa Rica",
  "Puerto Rico",
  "Seychelles",
];
