import DashboardIcon from "@mui/icons-material/Dashboard";
import AutoStoriesIcon from "@mui/icons-material/AutoStories";
import AirplanemodeActiveIcon from "@mui/icons-material/AirplanemodeActive";
import LocationOnIcon from "@mui/icons-material/LocationOn";
import MapIcon from "@mui/icons-material/Map";
import RateReviewIcon from "@mui/icons-material/RateReview";
import ArticleIcon from "@mui/icons-material/Article";
import SettingsIcon from "@mui/icons-material/Settings";
import AssignmentIcon from "@mui/icons-material/Assignment";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import BookOnlineIcon from "@mui/icons-material/BookOnline";

import RouteIcon from "@mui/icons-material/Route";
import RemoveRedEyeIcon from "@mui/icons-material/RemoveRedEye";
import CurrencyExchangeIcon from "@mui/icons-material/CurrencyExchange";
import CollectionsIcon from "@mui/icons-material/Collections";
import ContactSupportIcon from "@mui/icons-material/ContactSupport";

export const navItems = [
  {
    id: "home",
    label: "Home",
    path: "/",
  },
  {
    id: "trekking",
    label: "Trekking",
    path: "/trekking",
  },
  {
    id: "kailashTours",
    label: "Kailash Tours",
    path: "/package/kjfdf",
  },
  {
    id: "aboutus",
    label: "About Us",
    path: "/aboutus",
  },
  {
    id: "activities",
    label: "Activities",
    path: "/activities",
  },
  {
    id: "dayTour",
    label: "Day Tour",
    path: "/day-tour",
  },
  {
    id: "nepalTour",
    label: "Nepal Tour",
    path: "/nepal-tour",
  },
  {
    id: "admin-dashboard",
    label: "Admin View",
    path: "/admin",
  },
  {
    id: "contact",
    label: "Contact",
    path: "/contact",
  },
];
export const adminNavItems = [
  {
    id: "dashboard",
    icon: <DashboardIcon />,
    label: "Dashboard",
    path: "",
  },
  {
    id: "pages",
    icon: <AutoStoriesIcon />,
    label: "Pages",
    path: "pages",
  },
  {
    id: "packages",
    icon: <AirplanemodeActiveIcon />,
    label: "Packages",
    path: "packages",
  },
  {
    id: "destination",
    icon: <LocationOnIcon />,
    label: "Destination",
    path: "destination",
  },
  {
    id: "regions",
    icon: <MapIcon />,
    label: "Regions",
    path: "regions",
  },
  {
    id: "testimonials",
    icon: <RateReviewIcon />,
    label: "Testimonials",
    path: "testimonials",
  },
  {
    id: "blogs",
    icon: <ArticleIcon />,
    label: "Blogs",
    path: "blogs",
  },
  {
    id: "settings",
    icon: <SettingsIcon />,
    label: "Settings",
    path: "settings",
  },
  {
    id: "our-team",
    icon: <AssignmentIcon />,
    label: "Our Team",
    path: "our-team",
  },
  {
    id: "bookings",
    icon: <BookOnlineIcon />,
    label: "Bookings",
    path: "bookings",
  },
  {
    id: "admins",
    icon: <AccountCircleIcon />,
    label: "Admins",
    path: "admins",
  },
];
export const registrationFormControls = [
  {
    id: "name",
    type: "text",
    placeholder: "Enter your username",
    label: "Username",
  },
  {
    id: "email",
    type: "email",
    placeholder: "Enter your email",
    label: "Email",
  },
  {
    id: "password",
    type: "password",
    placeholder: "Enter your password",
    label: "Password",
  },
];

export const loginFormControls = [
  {
    id: "email",
    type: "email",
    placeholder: "Enter your email",
    label: "Email",
    componentType: "input",
  },
  {
    id: "password",
    type: "password",
    placeholder: "Enter your password",
    label: "Password",
    componentType: "input",
  },
];
export const packageNavItems = [
  {
    id: "overview",
    icon: <RemoveRedEyeIcon />,
    label: "Overview",
    path: "#overview",
  },
  {
    id: "itinerary",
    icon: <RouteIcon />,
    label: "Itinerary",
    path: "#itinerary",
  },
  {
    id: "map",
    icon: <MapIcon />,
    label: "Map",
    path: "#map",
  },

  {
    id: "costInclueExclude",
    icon: <CurrencyExchangeIcon />,
    label: "Cost Include/Exclude",
    path: "#costInclueExclude",
  },
  {
    id: "gallery",
    icon: <CollectionsIcon />,
    label: "Gallery",
    path: "#gallery",
  },
  {
    id: "faq",
    icon: <ContactSupportIcon />,
    label: "FAQ",
    path: "#faq",
  },

  {
    id: "review",
    icon: <RateReviewIcon />,
    label: "Review",
    path: "#review",
  },
];

export const pkgDetail = {
  headerImage: "/images/km.png",
  headerTitle: "Kailash Overland Tour - 13 Days",
  packageInformation: [
    {
      id: "duration",
      label: "Duration",
      information: "14 Days",
    },
    {
      id: "difficulty",
      label: "Difficulty",
      information: "Strenuous",
    },
    {
      id: "bestWeather",
      label: "Best Weather",
      information: "March-May & Sep-Nav",
    },
    {
      id: "maxAltitude",
      label: "Max Altitude",
      information: "5545m",
    },
  ],
  overviewTitle: "Experience the Allure of the Mount Kailash Overland Tour",
  overviewContent:
    "Leaf Holidays and Expedition provides you with the best experience. This is an extraordinary adventure that deals with spirituality, the beauty of Kailash, and the culture as well. The journey to Mount Kailash and Lake Manasarovar located in Tibet, China is quite amazing. It’s not just an expedition but has a spiritual value. The Mount Kailash Overland Tour is a typical adventure and makes your soul amazing. Mostly the Pilgrims visit Mount Kailash and Lake Manasarovar as it is considered one of the Holiest Peaks in Hinduism and Buddhism.It is believed that Mount Kailash is the abode of Lord Shiva and Lake Manasarovar is located nearer to his sacred lake and is believed to have a holy property. Yet with every step, you’ll also be moving closer to the spiritual essence of Mount Kailash. You may join us as we provide you with the best experience while traveling with us.",
  itinerary: [
    {
      id: 1,
      title: "Day 1: Arrival in Kathmandu (1400m)",
      details:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum rutrum at. Mauris ultricies et mauris convallis consectetur. Cras pulvinar dolor eget felis vulputate, sit amet vestibulum erat ultricies. Ut at velit quam. Mauris porttitor suscipit ipsum sit amet dapibus. Aliquam lobortis vulputate nunc. Fusce pretium ultricies urna sed consectetur. Praesent ut egestas ex. Morbi eu lacinia enim. Nullam id erat elementum, porta eros fringilla, rutrum enim. Pellentesque iaculis felis ac malesuada vestibulum. Etiam facilisis, metus sed pretium tristique, nibh felis pretium arcu, at vehicula enim tortor sit amet urna.",
    },
    {
      id: 2,
      title: "Day 2: Kathmandu to Lukla by flight",
      details:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum rutrum at. Mauris ultricies et mauris convallis consectetur. Cras pulvinar dolor eget felis vulputate, sit amet vestibulum erat ultricies. Ut at velit quam. Mauris porttitor suscipit ipsum sit amet dapibus. Aliquam lobortis vulputate nunc. Fusce pretium ultricies urna sed consectetur. Praesent ut egestas ex. Morbi eu lacinia enim. Nullam id erat elementum, porta eros fringilla, rutrum enim. Pellentesque iaculis felis ac malesuada vestibulum. Etiam facilisis, metus sed pretium tristique, nibh felis pretium arcu, at vehicula enim tortor sit amet urna.",
    },
    {
      id: 3,
      title: "Day 3: Lukla to Namche Bazaar",
      details:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum rutrum at. Mauris ultricies et mauris convallis consectetur. Cras pulvinar dolor eget felis vulputate, sit amet vestibulum erat ultricies. Ut at velit quam. Mauris porttitor suscipit ipsum sit amet dapibus. Aliquam lobortis vulputate nunc. Fusce pretium ultricies urna sed consectetur. Praesent ut egestas ex. Morbi eu lacinia enim. Nullam id erat elementum, porta eros fringilla, rutrum enim. Pellentesque iaculis felis ac malesuada vestibulum. Etiam facilisis, metus sed pretium tristique, nibh felis pretium arcu, at vehicula enim tortor sit amet urna.",
    },
    {
      id: 4,
      title: "Day 4: Namche Bazaar to Phakding",
      details:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum rutrum at. Mauris ultricies et mauris convallis consectetur. Cras pulvinar dolor eget felis vulputate, sit amet vestibulum erat ultricies. Ut at velit quam. Mauris porttitor suscipit ipsum sit amet dapibus. Aliquam lobortis vulputate nunc. Fusce pretium ultricies urna sed consectetur. Praesent ut egestas ex. Morbi eu lacinia enim. Nullam id erat elementum, porta eros fringilla, rutrum enim. Pellentesque iaculis felis ac malesuada vestibulum. Etiam facilisis, metus sed pretium tristique, nibh felis pretium arcu, at vehicula enim tortor sit amet urna.",
    },
    {
      id: 5,
      title: "Day 5: Phakding to Tengboche",
      details:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum rutrum at. Mauris ultricies et mauris convallis consectetur. Cras pulvinar dolor eget felis vulputate, sit amet vestibulum erat ultricies. Ut at velit quam. Mauris porttitor suscipit ipsum sit amet dapibus. Aliquam lobortis vulputate nunc. Fusce pretium ultricies urna sed consectetur. Praesent ut egestas ex. Morbi eu lacinia enim. Nullam id erat elementum, porta eros fringilla, rutrum enim. Pellentesque iaculis felis ac malesuada vestibulum. Etiam facilisis, metus sed pretium tristique, nibh felis pretium arcu, at vehicula enim tortor sit amet urna.",
    },
  ],
  costInclude: [
    {
      id: 1,
      content:
        "Cost Include Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 2,
      content:
        "Cost Include Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 3,
      content:
        "Cost Include Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 4,
      content:
        "Cost Include Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 5,
      content:
        "Cost Include Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
  ],
  costExclude: [
    {
      id: 1,
      content:
        "Cost Exclude Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 2,
      content:
        "Cost Exclude Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 3,
      content:
        "Cost Exclude Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 4,
      content:
        "Cost Exclude Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
    {
      id: 5,
      content:
        "Cost Exclude Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pharetra justo neque, eget accumsan ipsum",
    },
  ],
  mapImage: "/images/map.jpg",
};

export const countries = [
  "Andorra",
  "French Southern and Antarctic Lands",
  "Laos",
  "Canada",
  "Nigeria",
  "Vanuatu",
  "Czechia",
  "Malawi",
  "Mali",
  "Iceland",
  "Norway",
  "Saint Vincent and the Grenadines",
  "Guadeloupe",
  "Chile",
  "Bermuda",
  "Kuwait",
  "Dominica",
  "Montenegro",
  "United States Virgin Islands",
  "Cameroon",
  "Sri Lanka",
  "China",
  "Bangladesh",
  "Sweden",
  "Grenada",
  "Turkey",
  "Guinea",
  "Tanzania",
  "Rwanda",
  "Singapore",
  "Morocco",
  "Saint Barthélemy",
  "Iraq",
  "Brunei",
  "Isle of Man",
  "North Korea",
  "Iran",
  "Curaçao",
  "Paraguay",
  "Albania",
  "Tajikistan",
  "Bolivia",
  "Austria",
  "Saint Kitts and Nevis",
  "United States Minor Outlying Islands",
  "Colombia",
  "Kosovo",
  "Belize",
  "Guinea-Bissau",
  "Marshall Islands",
  "Myanmar",
  "French Polynesia",
  "Brazil",
  "Croatia",
  "Somalia",
  "Afghanistan",
  "Anguilla",
  "Cook Islands",
  "New Zealand",
  "Eritrea",
  "Cambodia",
  "Bahamas",
  "Belarus",
  "Norfolk Island",
  "Tuvalu",
  "South Georgia",
  "Mauritania",
  "New Caledonia",
  "Bulgaria",
  "Mozambique",
  "Niue",
  "Estonia",
  "Italy",
  "Malta",
  "Slovenia",
  "India",
  "Peru",
  "Burundi",
  "Lithuania",
  "United States",
  "Honduras",
  "Tonga",
  "Saudi Arabia",
  "Suriname",
  "Qatar",
  "Gibraltar",
  "Northern Mariana Islands",
  "Mauritius",
  "Barbados",
  "Réunion",
  "British Indian Ocean Territory",
  "Syria",
  "Egypt",
  "São Tomé and Príncipe",
  "Kiribati",
  "Timor-Leste",
  "Lesotho",
  "Solomon Islands",
  "Libya",
  "South Korea",
  "Liechtenstein",
  "Nicaragua",
  "Ecuador",
  "Maldives",
  "Algeria",
  "Kyrgyzstan",
  "Finland",
  "Kenya",
  "Cuba",
  "Montserrat",
  "Poland",
  "Åland Islands",
  "Ethiopia",
  "Togo",
  "Bosnia and Herzegovina",
  "Uruguay",
  "Guam",
  "Cape Verde",
  "Chad",
  "Vatican City",
  "Palau",
  "Haiti",
  "Yemen",
  "Eswatini",
  "Zimbabwe",
  "Greece",
  "Israel",
  "Saint Martin",
  "Antigua and Barbuda",
  "Cyprus",
  "Sint Maarten",
  "Monaco",
  "Fiji",
  "Ukraine",
  "Martinique",
  "Hong Kong",
  "Portugal",
  "Bhutan",
  "Nepal",
  "France",
  "Ireland",
  "United Arab Emirates",
  "Guernsey",
  "Saint Lucia",
  "Dominican Republic",
  "Serbia",
  "Botswana",
  "Ivory Coast",
  "Ghana",
  "Comoros",
  "Azerbaijan",
  "United Kingdom",
  "Central African Republic",
  "Palestine",
  "Caribbean Netherlands",
  "Taiwan",
  "Pitcairn Islands",
  "San Marino",
  "Svalbard and Jan Mayen",
  "Djibouti",
  "Wallis and Futuna",
  "Denmark",
  "Papua New Guinea",
  "Madagascar",
  "Bouvet Island",
  "Hungary",
  "Tokelau",
  "Trinidad and Tobago",
  "Gambia",
  "Luxembourg",
  "Cocos (Keeling) Islands",
  "Republic of the Congo",
  "Argentina",
  "DR Congo",
  "Greenland",
  "Jordan",
  "Belgium",
  "Switzerland",
  "Indonesia",
  "Lebanon",
  "Malaysia",
  "Cayman Islands",
  "Slovakia",
  "Armenia",
  "Christmas Island",
  "Mongolia",
  "Saint Pierre and Miquelon",
  "Japan",
  "South Africa",
  "Philippines",
  "Micronesia",
  "Germany",
  "Latvia",
  "Jamaica",
  "Macau",
  "Nauru",
  "Faroe Islands",
  "Guyana",
  "Burkina Faso",
  "Sudan",
  "Russia",
  "Mayotte",
  "Australia",
  "Liberia",
  "Mexico",
  "Tunisia",
  "Aruba",
  "Kazakhstan",
  "Oman",
  "French Guiana",
  "Niger",
  "Turkmenistan",
  "Sierra Leone",
  "Samoa",
  "Senegal",
  "Georgia",
  "Namibia",
  "South Sudan",
  "Thailand",
  "Bahrain",
  "Falkland Islands",
  "Jersey",
  "Vietnam",
  "Guatemala",
  "Moldova",
  "North Macedonia",
  "Uzbekistan",
  "Romania",
  "Uganda",
  "El Salvador",
  "Zambia",
  "Gabon",
  "Equatorial Guinea",
  "Spain",
  "Netherlands",
  "British Virgin Islands",
  "Benin",
  "Pakistan",
  "Panama",
  "Turks and Caicos Islands",
  "Angola",
  "American Samoa",
  "Venezuela",
  "Costa Rica",
  "Puerto Rico",
  "Seychelles",
];
